#This is a file to config the parameters

# Seed
seed: 1
dir_ids:"/usr/not-backed-up/scnc/data/datasets/ukbb_roi.csv"
dir_dataset: "/usr/not-backed-up/scnc/data/datasets/"


# Model Parameters
latent-dim: 512
optimizer: "adam"


# Learning Parameters
batch_size: 4
epochs: 200
lr: 1e-3

#Additional
coments:
